service: serverless-offline-dynamodb
frameworkVersion: "2"

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  webpack:
    webpackConfig: "./webpack.config.js"
    packager: "npm"
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-dynamodb-local
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs12.x
  memorySize: 512
  versionFunctions: false
  deploymentBucket:
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
        - s3:*
        - ses:*
      Resource: "*"

package:
  individually: true

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: user
          method: get
          cors: true

resources:
  - Resources: ${file(./config/dynamoDB.yaml)}
